### ISSUE TITLE
redoc and swagger interfaces not correct?

### ISSUE THREAD

**Issue by dblodgett-usgs** [opengeospatial/ogcapi-environmental-data-retrieval#326] opened 2021-11-24 20:33 UTC
This interface: https://developer.ogc.org/api/edr/index.html is not really clear to me. The "instance metadata" section seems screwed up? 

Why aren't we using OpenAPI -- which seems much more approachable? https://developer.ogc.org/api/edr/edr_api.html

**Comment by ghobona** [comment] 2021-11-24 20:47
@dblodgett-usgs Please see attached, we provide links to both the SwaggerUI example and the ReDoc example. They are different views of similar OpenAPI definition document examples. We've done a similar thing with OGC API - Features (that page has 4 examples).

<img width="1421" alt="Screenshot 2021-11-24 at 20 41 49" src="https://user-images.githubusercontent.com/18121038/143310624-7a0ceac9-febc-4bc4-ac52-aaa3c83c5d85.png">

**Comment by dblodgett-usgs** [comment] 2021-11-24 22:19
Any way to link to them from within the swagger and/or redoc views?

@m-burgoyne -- can you look at these and check if the instances section seems strange? Why does location show up on the instance section but not the other query patterns? Similarly, the collections metadata has items, instances, and locations. Seems kind of arbitrary that those are included there and down below in data queries. 

![image](https://user-images.githubusercontent.com/1492803/143319827-af203918-a31a-4f26-bfea-18dc9b7ca357.png)

**Comment by ghobona** [comment] 2021-11-24 22:35
Please clarify what you mean by 'link to them'.

If it's to facilitate discussion on GitHub you could link to the line number on the yaml document in the repo. For example, Line 660 on the working copy https://github.com/opengeospatial/ogcapi-environmental-data-retrieval/blob/master/standard/openapi/EDR_OpenAPI.yaml#L660

A screenshot probably works best though.

**Comment by dblodgett-usgs** [comment] 2021-11-26 14:26
@gobe -- here: 
![image](https://user-images.githubusercontent.com/1492803/143595073-0a41ce90-4a2d-490c-94ad-3945380611e4.png)
 
The "EDRGoeJSON Properties" is rendered, but there is no way to get a link to the actual EDR GeoJSON schema. There's even some pop up text in there that gives a path "schema/edrProperties.yml" -- this file. https://github.com/opengeospatial/ogcapi-environmental-data-retrieval/blob/master/standard/openapi/schemas/edrProperties.yaml 

It would be great to have some better cross-linking of these schemas as they are really core to the functioning of the API for developers who want to use hypermedia.

**Comment by chris-little** [comment] 2021-12-02 13:56
EDR API SSG #66 agreed to create a fix to add the missing queries to the `instances` endpoint.

**Comment by m-burgoyne** [comment] 2021-12-02 16:17
@dblodgett-usgs I think theOpenAPI  issue was caused by an invalid Tag in the OpenAPI docs, removed the `Instance Metadata` tag so the instance locations query will now be grouped with the other queries under `Instance data queries`.

**Comment by chris-little** [comment] 2021-12-09 19:02
Fixed by recent PR, now merged . EDR API SWG 67 agreed to close.

**Closed by chris-little** 2021-12-09 19:02 UTC
