### ISSUE TITLE
PublicComment 1.1: Variables in channel?

### ISSUE THREAD

**Issue by m-mohr** [opengeospatial/ogcapi-environmental-data-retrieval#530] opened 2024-03-26 23:07 UTC
I'm currently reading through https://docs.ogc.org/DRAFTS/23-057.html as part of the RFC.

In section 8.2.4 I'm wondering how the variables in the channel properties work. There's an example that uses {collectionId}, but I'm unsure where the variables are defined etc. Or are these channels somehow defined externally and are "hardcoded" values that e.g. refer back to specific endpoints? I think this should be explained better. There's not a lot of info on channels in 8.2 (seems to come in 9, but that's after 8.2 so leaves the reader confused).

---

Looking a bit into the future: I think this would also be great extension for STAC API, which could be built on top of EDR PubSub. Does the specification allow extensions, e.g. that a potential channel in STAC could be a specific search query such as `/search?collections=A,B,C&datetime=2020-01-01/..`?

**Comment by chris-little** [comment] 2024-03-26 23:23
@tomkralidis @m-burgoyne For your info.

**Comment by ilkkarinne** [comment] 2024-03-27 13:54
As requested by Steve Olson at the OGC MM Delft meeting, I'm providing a quick use case for spatial filtering functionality at PubSub API provider side. Note that this is not a request to make any changes in the current specification. I'm aware that due to varying technical capabilities in the underlying implementation protocols it may not be feasible to specify a general solution to this issue:

It would be very useful in some use cases to be able to attach a simple BBOX filter to the collection item subscription. Let's say that there is a collection for point weather forecasts of cities globally. Living in Europe I would like to be able to receive new forecast updates of only the cities located in Europe. I can of course filter the results at client side, but this may result in a majority on subscribed notifications to be sent over just to be immediately discarded at the client side.

I'm also aware that implementing a subscription filters at the provider side would require allocating additional computing and memory resources at the provider side.

**Comment by m-burgoyne** [comment] 2024-03-28 09:25
Digging into the  [AsyncAPI spec](https://www.asyncapi.com/en) the [Operations Bindings object](https://www.asyncapi.com/docs/reference/specification/v3.0.0#operationBindingsObject) supports the definition of protocol specific capabilities.  The [AWS SNS definition](https://github.com/asyncapi/bindings/blob/master/sns/README.md#operation) and example of how filtering would be defined

**Comment by chris-little** [comment] 2024-04-11 17:05
EDR API SWG 115 discussed this. The issue is that most use of variables and filtering is protocol specific and has to be addressed through the AsyncAPI schemas. General filtering of resources is not really a PubSub functionality.

Client side filtering is possible, but again not a function of the PubSub approach. 

@m-mohr We do not propose to alter the specification in response to this issue.

**Comment by m-mohr** [comment] 2024-04-11 21:25
I don't think this issue needs a functional change, but a bit of either restructuring, or better linking, or better descriptions. 
Something that is occuring in 8 is only introduced in 9, that's not ideal and confusing.

**Comment by tomkralidis** [comment] 2024-04-12 01:13
@m-mohr I've added some explanation around the link channel in #539.  The variables in the examples have been replaced with proper examples (because the channel property should not have tokens; they were only there for example purposes).

**Comment by chris-little** [comment] 2024-05-01 16:57
@m-mohr Are you happy to close this issue once @tomkralidis PR #539 merged?

**Comment by m-mohr** [comment] 2024-05-01 22:06
Looks good.

**Closed** 2024-05-07 17:42 UTC
Labels: EDR Part 2
